minimum_pre_commit_version: 1.21.0
fail_fast: false
default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v1.1.12
    hooks:
      - id: clang-format
        args: [-i, --style=file]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
