server {
    listen 8080;
    server_name localhost;
    
    root ./www; 

    client_max_body_size 1048576; # 1MB

    error_page 400 /errors/400.html;
    error_page 401 /errors/401.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 411 /errors/411.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;
    error_page 501 /errors/501.html;

    # index page for every location
    index index.html;

    location / {
			limit_except GET POST;
    }

    location /upload {
			limit_except GET POST;
    }

    location /uploads {
			limit_except GET POST DELETE;
			autoindex on; # shows list of files
    }

    location /delete {
			limit_except GET DELETE;
    }

		location /redirected_here {
			limit_except GET;
		}
		
		location /redirect {
			return 301 /redirected_here;
		}

		location /assets {
			limit_except GET; # can only get styles.css and script.js files
    }

# to return error 405, only DELETE is allowed, so when a request (GET)
# is made, it can't proceed:
		location /method_not_allowed {
			limit_except DELETE;
		}

# to test error 401:
		location /auth_required {
			limit_except GET;
			auth_required on;
		}

    location /cgi-bin {
			limit_except GET POST;
			cgi_ext .py;
			cgi_path /usr/bin/python3;
    }
}