# server 1
server {
    listen 127.0.0.1:8080;
    server_name 1;

    root ./www;
    location / {
			limit_except GET POST;
    }
}

# server 2
server {
    listen 8081;
    server_name 2;

    root ./www;
    location / {
			limit_except GET POST;
    }
}
