# comment 1 {}/////{}
server {
    listen 127.0.0.1:8080; # comment 2 {}/////{}
    server_name basic;

    root ./www;
    location / { # comment 3 {}/////{}
			limit_except GET;
    }
}
# comment 4 {}/////{}
