server {
    listen 127.0.0.1:8080;
    server_name localhost;

    root ./www;

    client_max_body_size 1048576; # 1MB

    # index page for every location
    index index.html;

    location / {
			limit_except GET;
    }

    location /post_body {
			limit_except GET POST;
			client_max_body_size 100;
    }

    location /directory {
			root 42_tester/YoupiBanane;
			limit_except GET POST;
			index youpi.bad_extension;
    }
    
	cgi_ext .bla;
	cgi_path ./42_tester/cgi_tester;
}
