server {
    listen 8080;
    server_name webserv;

    root ./www/webserv;
    client_max_body_size 1048576; # 1MB
    error_page 404 /errors/404.html;
    index index.html;

    location / {
        limit_except GET POST;
    }
    location /upload {
        upload_store /uploads;
        limit_except GET POST;
    }
    location /uploads {
        limit_except GET POST DELETE;
        autoindex on;
    }
    location /delete {
        limit_except GET DELETE;
    }
		location /forbidden {
        limit_except GET;
				autoindex off; # for not listing an empty directory, but returning 403, since there's no index.html
    }
    location /assets {
        limit_except GET;
    }
}

server {
    listen 8080;
    server_name other.server;

    root ./www/other-server;
    client_max_body_size 1048576; # 1MB
    error_page 404 /errors/404.html;
    index index.html;

    location / {
        limit_except GET POST;
    }
    location /upload {
        upload_store /uploads;
        limit_except GET POST;
    }
    location /uploads {
        limit_except GET POST DELETE;
        autoindex on;
    }
    location /delete {
        limit_except GET DELETE;
    }
		location /forbidden {
        limit_except GET;
				autoindex off; # for not listing an empty directory, but returning 403, since there's no index.html
    }
    location /assets {
        limit_except GET;
    }
}
