server {
    listen 8080;
    server_name localhost;
    root ./www;

    # Запрещить GET на некоторых routes
    location / {
        limit_except GET;
    }

    # Запрещить DELETE везде кроме папки
    location /delete_me {
        limit_except DELETE;
    }

    location /upload {
            client_max_body_size 50;
            upload_store /uploads;
			limit_except GET POST;
    }

    # Ограничить размер тела
    client_max_body_size 50;

    # Редирект
    location /redirect/ {
        return 301 /redirected_here/;
    }

    # Обработка CGI
    location /cgi-bin {
        limit_except GET POST;
		cgi_ext .pl;
		cgi_path /usr/bin/perl;
		cgi_ext .py;
		cgi_path /usr/bin/python3;
    }

    # Ошибка 403
    location /forbidden/ {
        limit_except DELETE;
    }
}
