server {
    listen 127.0.0.1:8082;
    server_name webserv;

    root ./www/webserv;
    client_max_body_size 1048576; # 1MB
    error_page 404 /errors/404.html;

    location / {
		limit_except GET POST;
		index index.html;
		autoindex off;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name other_server;

    root ./www/other_server;
    client_max_body_size 1048576; # 1MB
    error_page 404 /errors/404.html;

    location / {
		limit_except GET POST;
		index index.html;
		autoindex off;
	}
}

server {
    listen 127.0.0.1:8080;
    server_name other_server;

    root ./www/other_server;
    client_max_body_size 1048576; # 1MB
    error_page 404 /errors/404.html;

    location / {
		limit_except GET POST;
		index index.html;
		autoindex off;
	}
}
